org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.23
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

geckolib_version=4.8.4

create_version = 6.0.8-289
ponder_version = 1.0.91
flywheel_version = 1.0.5
registrate_version = MC1.20-1.3.3

mod_id=shadered
mod_name=Shadered
mod_license=Creative Commons Attribution 4.0 International
mod_version=2.0
mod_group_id=com.noodlegamer76
mod_authors=Noodlegamer76
mod_description=
